# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1035x691 | 
    self.driver.set_window_size(1035, 691)
    # 3 | click | id=APjFqb | 
    self.driver.find_element(By.ID, "APjFqb").click()
    # 4 | type | id=APjFqb | Tanger
    self.driver.find_element(By.ID, "APjFqb").send_keys("Tanger")
    # 5 | close |  | 
    self.driver.close()
  
